name: Maven Test

on:
  push:
    branches: [ master, multipaper ]
  pull_request:
    branches: [ master, multipaper ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: ${{ github.workspace }}/build/**/*
